vault:
  enabled: true
  clientId: ${client_id}
  clientSecret: ${client_secret}
  applicationNamespaces:
%{ for namespace in allowed_namespaces ~}
    - ${namespace}
%{ endfor ~}
hcloud:
  enabled: ${hcloud_token_enabled}
  token: ${hcloud_token}
  namespace: {$hcloud_namespace}
