name: Prepare Terraform plan
on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform init
        run: terraform init --input=false
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform apply
        id: apply
        run: terraform apply --input=false
